#!/bin/bash
### TEST FOR RELEASE GROUP KEY. EXIT IF PRESENT
PLIST=/var/db/.com.YOUR-ORG.host-info.plist
KEY="release_group"
KEY_TEST="defaults read $PLIST $KEY"
if ($KEY_TEST) > /dev/null 2>&1; then
	echo "release_group found. exiting"
	exit
fi
### RELEASE GROUP ASSIGNMENT
###   generates a random # between 0-19, then using probability, assigns to a Release Group 
###   by adding a release group KEY + string to the host-info.plist
###   Possible results: 0 (1/20) = 5% chance (RG-1), 1-3 (3/20) = 15% chance (RG-2), 
###   4-9 (6/20) = 30% chance (RG-3), all other #s (10-19) (10/20) = 50% chance (RG-4)
# generate a random # between 0-19
random_number=$((0 + $RANDOM % 19))
echo $random_number
# if random_number = 0, assign RG-1 and exit
if [[ "$random_number" -eq "0" ]]; then
	/usr/libexec/PlistBuddy -c "Add :release_group string RG-1" /var/db/.com.sophos.host-info.plist
	/usr/local/jamf/bin/jamf recon
	echo "Mac assigned to RG-1"; exit
	# if random_number is ge 1, le 3, assign RG-2 and exit
elif [ "$random_number" -ge 1 ] && [ "$random_number" -le 3 ]; then
	/usr/libexec/PlistBuddy -c "Add :release_group string RG-2" /var/db/.com.sophos.host-info.plist
	/usr/local/jamf/bin/jamf recon
	echo "Mac assigned to RG-2"; exit
	# if random_number is ge 4, le 9, assign RG-3 and exit
elif [ "$random_number" -ge 4 ] && [ "$random_number" -le 9 ]; then
	/usr/libexec/PlistBuddy -c "Add :release_group string RG-3" /var/db/.com.sophos.host-info.plist
	echo "Mac assigned to RG-3"; exit	
	# else assign RG-4
else
	/usr/libexec/PlistBuddy -c "Add :release_group string RG-4" /var/db/.com.sophos.host-info.plist
	/usr/local/jamf/bin/jamf recon
	echo "Mac assigned to RG-4"; exit
fi
